### ISSUE TITLE
Helium Stats and prices no longer working?

### ISSUE THREAD

**Issue by liviooo** [enes-oerdek/Home-Assistant-Helium-Integration#10]
Since Aug. 16th. the Helium stats and prices are no longer working. The last updates fixed the other integration entities, but price and stats became inactive since.
Any info on that?
<img width="1284" alt="Screenshot 2023-08-25 at 14 04 43" src="https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/23534/b5aa8f99-8e42-486b-be97-5c2c7016ec7f">
<img width="1240" alt="Screenshot 2023-08-25 at 14 04 11" src="https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/23534/2eafb74d-6643-409b-a58e-93b10dab24c0">

**Comment by enes-oerdek** [comment]
If you updated on 16th to the latest version of the integration, it might result in the behaviour you mention in this issue:
https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/releases/tag/2.5

Solution is simple. Add two more configurations, so that you see also the entry for "Token Prices" and "Helium Stats" in your integration configurations. That should resolve the issue.

Please check and let me know.

**Comment by liviooo** [comment]
Thnx. That worked!

**Comment by enes-oerdek** [comment]
You are welcome. Your "old" integration entry has probably the label "Migrated". But should be no issue now, since you introduced the missing sensors by configuring the two entries.

Have fun using the integration. In case you have further questions or feedback, please create another issue.
