### ISSUE TITLE
Error all entities unavailable 

### ISSUE THREAD

**Issue by pbvdven** [enes-oerdek/Home-Assistant-Helium-Integration#9]
I have a new error all entities are unavailable integration version 2.4.3 

error in the log

Logger: homeassistant.components.sensor
Source: custom_components/helium_solana/api/backend.py:17
Integration: Sensor (documentation, issues) 
First occurred: 06:31:33 (2 occurrences) 
Last logged: 06:34:41

Error while setting up helium_solana platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/helium_solana/sensor.py", line 77, in async_setup_entry
    sensors = await get_sensors(wallets, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/sensor.py", line 128, in get_sensors
    response = await api_backend.get_data('hotspot-rewards2/'+str(wallet))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 28, in get_data
    response = await asyncio.to_thread(self.http_client, path, None, 'GET', headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 17, in http_client
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://solana.oerdek.com/hotspot-rewards2/4PPtWfiDvfHktRJ5zkSwVE71N8pTEFDofzDG65x7m2mA

Also I tried removing the integration and adding it again but now same as yesterday the integration gets addedd but without entities?

**Comment by jooslouw** [comment]
Same problem here since yesterday. I get the same log file error  (obviously with my walletID in the 500 Server Error line). I also updated to the latest version 2.4.3. I tried downgrading back to 2.4.2 without luck.
These were the chain of events:
I was on HASS 2023.7
I updated the Helium integration to version 2.4.3 via HACS
The Helium entities became unavailable after the restart.
I then upgraded my HASS to 2023.8
Helium entities still unavailable, then downgraded to 2.4.2
Helium entities still unavailable, then upgraded back to 2.4.3

**Comment by bttfw** [comment]
Same

**Comment by pbvdven** [comment]
Yes its working again. Thanks

**Comment by jooslouw** [comment]
Working again after reloading the Helium integration. Thanks

**Comment by MVerBerkmoes** [comment]
It came back after following the directions above, but all sensors are down with the same error.  😩

**Comment by roelvandermade** [comment]
Hi the issue clearly seems to be the backend, I noticed you are using a backend you maybe created yourself? There are several publically available official Solana API services, wouldn't it make it more sense to use one of those to get the required data?

**Comment by enes-oerdek** [comment]
> Hi the issue clearly seems to be the backend, I noticed you are using a backend you maybe created yourself? There are several publically available official Solana API services, wouldn't it make it more sense to use one of those to get the required data?

Unfortunately, it is not sufficient to just grab data from the api, and sometimes they cost money. I am running a very simple backend server, which costs me 3$ per month where I can provide all the needed calculations and processes to get the required data. Actually the currently existing issue is due to an external service no longer working. This integration is dependend on this endpoint: https://github.com/lthiery/hnt-explorer
https://hnt-explorer.herokuapp.com/v1/positions/vehnt
![grafik](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/5871793/d00009ed-b5a6-4e70-982b-73957153dbd4)


I will work on running this service as well on this integration's backend, to have better availability. Sorry again for the inconvenience.

**Comment by roelvandermade** [comment]
> > Hi the issue clearly seems to be the backend, I noticed you are using a backend you maybe created yourself? There are several publically available official Solana API services, wouldn't it make it more sense to use one of those to get the required data?
> 
> Unfortunately, it is not sufficient to just grab data from the api, and sometimes they cost money. I am running a very simple backend server, which costs me 3$ per month where I can provide all the needed calculations and processes to get the required data. Actually the currently existing issue is due to an external service no longer working. This integration is dependend on this endpoint: https://github.com/lthiery/hnt-explorer https://hnt-explorer.herokuapp.com/v1/positions/vehnt ![grafik](https://user-images.githubusercontent.com/5871793/259988107-d00009ed-b5a6-4e70-982b-73957153dbd4.png)
> 
> I will work on running this service as well on this integration's backend, to have better availability. Sorry again for the inconvenience.

Aha, clear. Yeah those external dependancies aren't the greatest to rely on ;-)
If you need any help server-side (config/tuning/etc.), let me know.

thanks!

**Comment by enes-oerdek** [comment]
Issue should be resolved. That external service is now also running on the backend. Availability should improve.

**Comment by roelvandermade** [comment]
> Issue should be resolved. That external service is now also running on the backend. Availability should improve.

so I noticed indeed, great work & thanks!

**Comment by jooslouw** [comment]
> Issue should be resolved. That external service is now also running on the backend. Availability should improve.

Excellent! Thanks Enes for the effort and great work. Much appreciated.
